version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - test
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    networks:
      - test
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  test:
    driver: bridge
